CREATE TABLE `QUOTES` (
  `GEMEENTE` varchar(255) DEFAULT NULL,
  `PERIODE` varchar(255) DEFAULT NULL,
  `NO` INT DEFAULT NULL,
  `GESCHIKT_VOOR_SLIDE` INT DEFAULT NULL,
  `QUOTE_VAN` varchar(255) DEFAULT NULL,
  `QUOTE` varchar(2550) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
