-- FIXDB.VRAGENLIJST_2022 definition

CREATE TABLE `VRAGENLIJST_2022` (
  `ID` int(11) DEFAULT NULL,
  `PERIODE` varchar(255) DEFAULT NULL,
  `GEMEENTE` varchar(255) DEFAULT NULL,
  `FIXTEAMS` int(11) DEFAULT NULL,
  `BETAALDE_WERKNEMERS` int(11) DEFAULT NULL,
  `VRIJWILLIGERS` int(11) DEFAULT NULL,
  `HUISHOUDENS_FIXED` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
