-- FIXDB.VRAGENLIJST_2024_Q4 definition

CREATE TABLE `VRAGENLIJST_2024_Q4` (
  `ID` int(11) DEFAULT NULL,
  `GEMEENTE` varchar(255) DEFAULT NULL,
  `FIXTEAMS` int(11) DEFAULT NULL,
  `HUISHOUDENS_FIXED` int(11) DEFAULT NULL,
  `HOEVAAK_LANGS` int(11) DEFAULT NULL,
  `BETAALDE_WERKNEMERS` int(11) DEFAULT NULL,
  `FTE` int(11) DEFAULT NULL,
  `VRIJWILLIGERS` int(11) DEFAULT NULL,
  `VRIJWILLIGERSUREN` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
